[build]
  publish = "/"
  command = ""

[functions]
  node_bundler = "esbuild"

# Corre cada 2 minutos (ajustá a gusto)
[functions."cron-dispatch"]
  schedule = "*/2 * * * *"


[[scheduled.functions]]
  path = "/.netlify/functions/cron-dispatch"
  schedule = "0 * * * *"
